"""WEEK 1 EXEMPLAR — Strategy S01: MA(10/50) crossover on AAPL (or offline twin).

This is the reference implementation for the whole course. Copy its SHAPE:
    thesis -> signal -> gross backtest -> net backtest -> OOS -> verdict

Run it:
    python week01_ma_crossover.py                # tries real data, falls back
    python week01_ma_crossover.py --offline      # deterministic, seeded
    python week01_ma_crossover.py --fast 20 --slow 100   # feel free to break it

It writes three artifacts next to itself:
    s01_tearsheet.txt      -> paste into your strategy note
    s01_verdict.md         -> the shipped verdict
    s01_equity.csv         -> the curve, for your own plots

DO NOT EDIT THIS FILE to make the numbers look better. Fork it to
strategies/S02_.../ when you build your second strategy.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import pandas as pd

# --- path bootstrap (bootcamp layout). In YOUR repo these three modules sit at
# --- the repo root (bootstrap.sh puts them there), so plain `import` works.
HERE = Path(__file__).resolve().parent


def _find_shared(start: Path) -> Path:
    """Walk up until we find bootcamp/shared/. In YOUR repo these three modules
    sit at the repo root (bootstrap.sh copies them there) and this returns None,
    so plain `import fetcher` / `import backtester` just works."""
    for p in [start, *start.parents]:
        cand = p / "shared"
        if (cand / "backtester").is_dir():
            return cand
    return start  # no shared/ found; assume flat layout


SHARED = _find_shared(HERE)
for mod in ("data-fetcher", "metrics-module", "backtester"):
    sys.path.insert(0, str(SHARED / mod))

from backtester import CostModel, backtest, buy_and_hold, walk_forward_splits  # noqa: E402
from fetcher import fetch, fetch_synthetic  # noqa: E402
from metrics import tear_sheet  # noqa: E402

SYMBOL = "AAPL"
SEED = 13          # chosen so the teaching case is honest, not flattering
START = "2015-01-01"
PERIODS = 2520     # ~10 years of business days


# --------------------------------------------------------------------------- #
# 1. THE  STRATEGY
# --------------------------------------------------------------------------- #
def thesis() -> str:
    """One paragraph, written BEFORE the code. If you cannot write it, you do not
    have a strategy, you have a curve fit."""
    return (
        "Trends in large-cap equities persist for weeks because of slow capital "
        "flows (index rebalancing, fund allocations) and because traders anchor "
        "to recent prices. A fast/slow moving-average crossover is the cheapest "
        "possible way to express 'be long when the short-term trend is up'. "
        "Expectation: it captures the middle of big moves, gets chopped in "
        "sideways markets, and should beat buy-and-hold on a risk-adjusted basis "
        "by cutting exposure during drawdowns -- IF the whipsaw cost is smaller "
        "than the drawdown it avoids. That is the bet."
    )


def signal(prices: pd.Series, fast: int = 10, slow: int = 50) -> pd.Series:
    """Long (1.0) when fast MA > slow MA, else flat (0.0).

    Look-ahead audit:
      - rolling(N).mean() at bar t uses bars t-N+1..t  -> PAST ONLY  [OK]
      - the backtester shifts this by 1 before trading  -> executed tomorrow
      - no `.shift(-1)`, no global min/max, no fillna(method='bfill')
    """
    if fast >= slow:
        raise ValueError(f"fast ({fast}) must be < slow ({slow})")
    ma_fast = prices.rolling(fast).mean()
    ma_slow = prices.rolling(slow).mean()
    out = (ma_fast > ma_slow).astype(float)
    out[ma_slow.isna()] = 0.0     # warm-up: flat, not "long by accident"
    return out


# --------------------------------------------------------------------------- #
# 2. THE RUN
# --------------------------------------------------------------------------- #
def load_prices(offline: bool) -> pd.Series:
    if offline:
        px = fetch_synthetic(SYMBOL, start=START, periods=PERIODS, seed=SEED)["close"]
        print(f"[data] OFFLINE synthetic twin of {SYMBOL} (seed={SEED})")
        return px
    try:
        px = fetch(SYMBOL, source="stooq")["adj_close"]
        px = px.loc[px.index >= START]
        print(f"[data] live {SYMBOL}: {len(px)} bars, {px.index[0].date()} -> {px.index[-1].date()}")
        return px
    except Exception as exc:
        print(f"[data] live fetch failed ({exc.__class__.__name__}); using synthetic twin")
        return fetch_synthetic(SYMBOL, start=START, periods=PERIODS, seed=SEED)["close"]


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--offline", action="store_true")
    ap.add_argument("--fast", type=int, default=10)
    ap.add_argument("--slow", type=int, default=50)
    ap.add_argument("--fee-bps", type=float, default=1.0)
    ap.add_argument("--slip-bps", type=float, default=5.0)
    ap.add_argument("--outdir", type=str, default=str(HERE))
    args = ap.parse_args(argv)

    out = Path(args.outdir)
    out.mkdir(parents=True, exist_ok=True)

    px = load_prices(args.offline)
    sig = signal(px, args.fast, args.slow)
    cm = CostModel(fee_bps=args.fee_bps, slippage_bps=args.slip_bps)

    # --- gross: the lie we tell ourselves first --------------------------- #
    gross = backtest(px, sig, cost_model=CostModel(0, 0, 0))
    # --- net: the number that ships --------------------------------------- #
    net = backtest(px, sig, cost_model=cm)
    # --- benchmark ---------------------------------------------------------- #
    bh = buy_and_hold(px, cost_model=cm)

    lines: list[str] = []
    say = lambda s="": (print(s), lines.append(s))

    say("=" * 62)
    say(f"  THESIS — S01 MA({args.fast}/{args.slow}) crossover on {SYMBOL}")
    say("=" * 62)
    for chunk in _wrap(thesis(), 58):
        say(f"  {chunk}")
    say()
    say(gross.summary(f"GROSS  (no costs)  MA {args.fast}/{args.slow}"))
    say()
    say(net.summary(f"NET ({args.fee_bps:.0f}+{args.slip_bps:.0f} bps)  MA {args.fast}/{args.slow}"))
    say()
    say(bh.summary("BENCHMARK  buy & hold"))
    say()

    # --- walk-forward: is it still alive out of sample? -------------------- #
    say("-" * 62)
    say("  WALK-FORWARD  (5 folds, 60% train, 5-bar embargo)")
    say("-" * 62)
    rows = []
    for i, (tr, te) in enumerate(walk_forward_splits(px.index, n_splits=5,
                                                     train_frac=0.6, embargo=5), 1):
        seg = px.loc[te]
        # FIXED parameters (10/50), so the signal can be computed once on the
        # full history: every bar's MA only looks BACKWARD, so slicing it into a
        # later window leaks nothing. From Week 5 onward, when you FIT params on
        # `tr`, you MUST recompute the signal inside the fold with train-fitted
        # params -- reusing a full-history signal then would be look-ahead.
        s = sig.reindex(te)
        r = backtest(seg, s, cost_model=cm)
        b = buy_and_hold(seg, cost_model=cm)
        ts = r.tear_sheet()
        rows.append({
            "fold": i,
            "test_start": str(te[0].date()),
            "test_end": str(te[-1].date()),
            "strat_sharpe": round(ts["sharpe"], 2),
            "strat_cagr": round(ts["cagr"] * 100, 1),
            "bh_cagr": round(b.tear_sheet()["cagr"] * 100, 1),
            "max_dd": round(ts["max_drawdown"] * 100, 1),
            "trades": ts["trades"],
        })
    oos = pd.DataFrame(rows)
    say(oos.to_string(index=False))
    say()
    say(f"  folds where strategy beat buy & hold (CAGR): "
        f"{int((oos['strat_cagr'] > oos['bh_cagr']).sum())}/{len(oos)}")
    oos_sharpe = float(oos["strat_sharpe"].mean())
    say(f"  mean out-of-sample Sharpe: {oos_sharpe:+.2f}   "
        f"(in-sample net Sharpe: {net.tear_sheet()['sharpe']:+.2f})")
    say()

    # --- the verdict -------------------------------------------------------- #
    n_ts, g_ts, b_ts = net.tear_sheet(), gross.tear_sheet(), bh.tear_sheet()
    beats_bh = n_ts["cagr"] > b_ts["cagr"]
    survives = n_ts["sharpe"] > 0.5 and n_ts["cagr"] > 0
    cost_hurt = g_ts["sharpe"] - n_ts["sharpe"]
    verdict = "SHIP (paper)" if (beats_bh and survives) else "KILL"

    say("=" * 62)
    say(f"  VERDICT: {verdict}")
    say("=" * 62)
    say(f"  beats buy & hold net of costs : {'YES' if beats_bh else 'NO'}"
        f"   ({n_ts['cagr']*100:+.1f}% vs {b_ts['cagr']*100:+.1f}% CAGR)")
    say(f"  survives costs                : Sharpe {g_ts['sharpe']:+.2f} gross "
        f"-> {n_ts['sharpe']:+.2f} net  (costs took {cost_hurt:.2f} of Sharpe)")
    say(f"  out-of-sample Sharpe          : {oos_sharpe:+.2f} vs "
        f"{n_ts['sharpe']:+.2f} in-sample")
    say(f"  total cost paid                : {n_ts['total_cost_paid']*100:.1f}% of capital "
        f"over {n_ts['trades']} trades")
    say()
    say("  Rule: KILL means it goes in the graveyard with a failure note.")
    say("        It does NOT mean you were wrong to build it. Week 1's job is")
    say("        to produce a KILL with a reason, not a SHIP with a hope.")

    # --- artifacts ---------------------------------------------------------- #
    (out / "s01_tearsheet.txt").write_text("\n".join(lines) + "\n")
    net.data[["position", "net_ret", "equity"]].to_csv(out / "s01_equity.csv")
    (out / "s01_verdict.md").write_text(
        verdict_md(args, n_ts, g_ts, b_ts, oos, oos_sharpe, verdict, beats_bh, survives)
    )
    print(f"\n[write] {(out / 's01_tearsheet.txt')}")
    print(f"[write] {(out / 's01_equity.csv')}")
    print(f"[write] {(out / 's01_verdict.md')}")
    return 0


def _wrap(text: str, width: int) -> list[str]:
    words, line, out = text.split(), "", []
    for w in words:
        if len(line) + len(w) + 1 > width:
            out.append(line)
            line = w
        else:
            line = f"{line} {w}".strip()
    if line:
        out.append(line)
    return out


def _md_table(df: pd.DataFrame) -> str:
    """DataFrame -> markdown table. Hand-rolled so the course needs no `tabulate`."""
    head = "| " + " | ".join(str(c) for c in df.columns) + " |"
    sep = "|" + "|".join("---" for _ in df.columns) + "|"
    body = ["| " + " | ".join(str(v) for v in row) + " |" for row in df.itertuples(index=False)]
    return "\n".join([head, sep, *body])


def verdict_md(args, n_ts, g_ts, b_ts, oos, oos_sharpe, verdict, beats_bh, survives) -> str:
    oos_tbl = _md_table(oos)
    return f"""# VERDICT — S01 MA({args.fast}/{args.slow}) crossover on {SYMBOL}

DATE:        (fill in)
STATUS:      {verdict}
SHIPPED BY:  (your name)

## Thesis
{thesis()}

## Rules
- Long 1.0 when MA({args.fast}) > MA({args.slow}), else flat 0.0
- Signal computed on today's close, executed at tomorrow's close (backtester shift)
- No leverage, no shorting, no stops

## Costs modeled
- fee {args.fee_bps:.1f} bps + slippage {args.slip_bps:.1f} bps per unit traded
- borrow 50 bps/yr on short notional (unused here: long-flat only)

## Results (net of costs, {n_ts['years']:.1f} yrs)
| metric | strategy | buy & hold |
|---|---|---|
| CAGR | {n_ts['cagr']*100:+.2f}% | {b_ts['cagr']*100:+.2f}% |
| Sharpe | {n_ts['sharpe']:+.2f} | {b_ts['sharpe']:+.2f} |
| Sortino | {n_ts['sortino']:+.2f} | {b_ts['sortino']:+.2f} |
| max DD | {n_ts['max_drawdown']*100:.2f}% | {b_ts['max_drawdown']*100:.2f}% |
| Calmar | {n_ts['calmar']:+.2f} | {b_ts['calmar']:+.2f} |
| ann. vol | {n_ts['ann_vol']*100:.2f}% | {b_ts['ann_vol']*100:.2f}% |
| hit rate | {n_ts['hit_rate']*100:.1f}% | {b_ts['hit_rate']*100:.1f}% |

- gross Sharpe (zero costs): {g_ts['sharpe']:+.2f}  ->  net: {n_ts['sharpe']:+.2f}
- costs removed {g_ts['sharpe'] - n_ts['sharpe']:.2f} of Sharpe
- total cost paid: {n_ts['total_cost_paid']*100:.1f}% of capital over {n_ts['trades']} trades

## Out-of-sample (walk-forward, 5 folds)
{oos_tbl}

- mean OOS Sharpe: {oos_sharpe:+.2f}  vs in-sample net Sharpe {n_ts['sharpe']:+.2f}

## Decision
- Beats buy & hold net of costs? **{'YES' if beats_bh else 'NO'}**
- Meets the viability bar (Sharpe > 0.5 and CAGR > 0)? **{'YES' if survives else 'NO'}**
- VERDICT: **{verdict}**

## Why (3 sentences, no hedging)
The crossover cut volatility versus buy & hold but gave up most of the return,
so net of costs it {'beat' if beats_bh else 'lost to'} simply holding the asset.
Costs removed {g_ts['sharpe'] - n_ts['sharpe']:.2f} of Sharpe across
{n_ts['trades']} trades, and the out-of-sample folds
{'degraded versus' if oos_sharpe < n_ts['sharpe'] * 0.7 else 'held up versus'} in-sample,
which means the edge (if any) is
{'fragile to' if oos_sharpe < n_ts['sharpe'] * 0.7 else 'robust to'} period choice.

## What I'd try next (max 2, each must be a new testable claim)
1. Add a trend filter (only take long signals above the 200-day MA) -- claim:
   it removes the whipsaw trades in sideways regimes.
2. Test on a 5-symbol universe -- claim: if this is a real trend effect it
   should show up on more than one asset.

## Graveyard
- If KILL: create `notes/failures/YYYY-MM-DD-S01-ma-crossover.md` using the
  Failure Note Template and add a row to `graveyard/graveyard.md`.
"""


if __name__ == "__main__":
    raise SystemExit(main())
